### ISSUE TITLE
Content not available even if user is member of passed groupIds

### ISSUE THREAD

**Issue by Vivekrajput20** [rabwill/generic-target-audience#1]
Promise.race is used in [TargetAudience.tsx](https://github.com/rabwill/generic-target-audience/blob/master/src/common/TargetAudience.tsx) 
```        
       Promise.race(proms).then(val => {
            this.setState({ canView: true }); //atleast one promise resolved
        });
```
But according to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) Promise.race() method returns a promise that fulfills or rejects as soon as one of the promises in an iterable fulfills or rejects, with the value or reason from that promise.
So if multiple groups are passed and user is member of any one of the passed groups but some other group's API call is rejected first, canView will remain false and user won't be able to see the content.

**Comment by rabwill** [comment]
Excellent pick up Vivek ! Thank you.

**Comment by Vivekrajput20** [comment]
@rabwill  I had also opened #2 for fixing this issue. Please look into it when you get time.

**Comment by rabwill** [comment]
Hey @Vivekrajput20 thanks so much for your input 🙂. Please feel free to clone this project and update the code as you would want to. This little project was only created for demo/blog purpose to show case some capabilities and is not really intended for any commercial aspects which is why it is not maintained. 
thanks again and happy coding 🎉
